### ISSUE TITLE
Sidecar container creation

### ISSUE THREAD

**Issue by seniordevops7** [cloudhippie/charts#63]
## Feature description
It would be awesome if you could add sidecar containers to execute a job once (for example: initialization of pgsql or mysql database).

**Comment by tboerger** [comment]
I just merged the pull request to optionally add init and sidecar containers to the deployments, thanks for the hint.

**Comment by seniordevops7** [comment]
Excellent! I give it a try, Thank you!

**Comment by tboerger** [comment]
Which chart are you using? Yopass or Semaphore? :)

**Comment by seniordevops7** [comment]
I'm using the semaphore chart, I tried it and it works for my deployment
